### ISSUE TITLE
Update gems

### ISSUE THREAD

**Issue by petecooper** [textpattern/txpmag-website#13]
Assuming we're keeping the mag site online for now, we need to update `Gemfile.lock`. There was one high severity issue with an out-of-date gem that's been resolved by https://github.com/textpattern/txpmag-website/commit/ea405d100438392759412467843d2e1bcebd5448 but it won't hurt to keep the guts up-to-date where we can.

**Comment by philwareham** [comment]
Done, although whether this project actually builds or not is another matter. Not used Ruby in my build chain for years.
